language: java
jdk:
  - openjdk11
sudo: true
dist: bionic
addons:
  apt:
    update: true
cache:
  directories:
    - $HOME/.m2

before_install:
  - rvm install 2.6.0
  - rvm use 2.6.0
  - sudo apt-get -y install nodejs-dev node-gyp libssl1.0-dev openjdk-8-jdk
  - sudo apt-get -y install npm
install:
  - gem install pdd -v 0.20.5
  - gem install xcop
script:
  - set -e
  - mvn clean install -Pqulice --errors --batch-mode
  - mvn clean
  - pdd -f /dev/null
